feat: Add Spanish localization
JonasWanke/timetable pull request #84
Opened 2021-06-25 17:41 UTC by paolovalerdi

2021-07-15 07:40 UTC, JonasWanke requested changes
Thanks for the contribution! It looks like there's one small typo, but after that is fixed, I'm happy to merge this PR

2021-07-15 07:40 UTC, JonasWanke commented on lib/src/localization.dart
> +        return const TimetableLocalizationEn();
```suggestion
        return const TimetableLocalizationEs();
```

2021-07-15 15:34 UTC, paolovalerdi commented
Oops 😅, I didn't realize, it's fixed, now and I also add it to the supported locales in the example app

2021-07-15 16:06 UTC, merged

2021-07-15 16:06 UTC, JonasWanke commented
Thanks for the quick fix :) I'll try to release it soon!

2021-08-02 10:14 UTC, JonasWanke commented
Sorry for the delay! This is now published as part of [v1.0.0-alpha.3](https://pub.dev/packages/timetable/versions/1.0.0-alpha.3/changelog#100-alpha3--2021-08-02). Thanks for contributing!