Adding languages- French and Portuguese
JonasWanke/timetable pull request #94
Opened 2021-08-06 19:07 UTC by simo9900

**Closes: #Issue**

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2021-08-06 19:07 UTC, simo9900 commented
Adding languages- French and Portuguese

2021-08-07 08:34 UTC, JonasWanke requested changes
Thanks for the contribution! I've added two minor comments; when these are fixed, I'm happy to merge this PR

2021-08-07 08:34 UTC, JonasWanke commented on lib/src/localization.dart
> +              "Material-/Cupertino-/WidgetApp's localizationsDelegates.",
Could you please revert these formatting changes?

2021-08-07 08:34 UTC, JonasWanke commented on README.md
> +Timetable currently offers localizations for Chinese, English, French, German, Italian, Japanese, Portuguese and Spanish.
```suggestion
Timetable currently offers localizations for Chinese, English, French, German, Italian, Japanese, Portuguese, and Spanish.
```

2021-08-07 09:40 UTC, JonasWanke approved these changes

2021-08-07 09:40 UTC, merged

2021-08-07 10:45 UTC, JonasWanke commented
This is now published as part of [v1.0.0-alpha.5](https://pub.dev/packages/timetable/versions/1.0.0-alpha.5/changelog#100-alpha5--2021-08-07). Thanks for contributing!